### PR TITLE
switched to jdk18u repo and jdk-18.0.1+10 tag.

### PR DESCRIPTION
**Pull request by mbien**
18.0.1 has just been released. I updated the properties file to point at the latest release.

It builds and the test `nb-javac test` was green too - haven't done any other testing.

I haven't looked at the release notes yet, but .1 updates usually include many fixes.

### CODE REVIEW

**Comment by mbien** [comment]
wait. that is the wrong tag! The 18u repo wasn't tagged yet, the release is supposed to be `18.0.1+10`, but there is no such tag in the repo yet.

**Review by jtulach — CHANGES_REQUESTED** [review]
We should run the build somehow...

**Comment by mbien** [comment]
https://github.com/openjdk/jdk18u/tree/jdk-18.0.1+10 tag is now in the repo

18.0.1 fixes three javac related bugs
https://bugs.openjdk.java.net/browse/JDK-8278373
https://bugs.openjdk.java.net/browse/JDK-8278834
https://bugs.openjdk.java.net/browse/JDK-8278930

delta is probably fairly small since not much happened language wise in Java 18.

**Review by jtulach — APPROVED** [review]
Builds fine now.

**Comment by mbien** [comment]
@jtulach will someone upload it to maven central or how does this work?

**Comment by jtulach** [comment]
The upload is usually done by @eppleton, but I cannot get in touch with him. Technically anyone can [follow the upload instructions](https://github.com/JaroslavTulach/nb-javac#publishing-to-maven-central--ossrh) and upload the bits to Maven central. Feel free to do so. I continue trying to reach Toni.

**Comment by dukescript** [comment]
I can do it, but I do not see the tag ( I only see idk-18+36) --Toni

**Comment by mbien** [comment]
> I can do it, but I do not see the tag ( I only see idk-18+36) --Toni

I linked it above, its on github: https://github.com/openjdk/jdk18u/tree/jdk-18.0.1+10

**Comment by jtulach** [comment]
Looks like Toni managed to upload the new version to [maven central](https://repo1.maven.org/maven2/com/dukescript/nbjavac/nb-javac/jdk-18.0.1+10/). Thank you, @dukescript!

**Pull request merged**
