### PR TITLE
Upgrading to jdk-22+33.

### PR DESCRIPTION
**Pull request by dbalek**
Upgrading to jdk-22+33.

### CODE REVIEW

**Review by jtulach — APPROVED** [review]
Let's merge once CI is green and let's publish the bits!

**Comment by jtulach** [comment]
Bits available as [#1164](https://oss.sonatype.org/content/repositories/comdukescript-1164/). OK to release?

**Comment by dbalek** [comment]
OK - see https://github.com/apache/netbeans/pull/6968

**Comment by jtulach** [comment]
OK. Bits [sent to Maven central](https://repo1.maven.org/maven2/com/dukescript/nbjavac/nb-javac/jdk-22+33/). Good luck!

**Pull request merged**
